local:
    logging_config: config/logging/local.conf
    crowd:
        user: corp
        password: eng718corp
    db:
        host: localhost
        db_name: www
    fts_db:
        host: localhost
        db_name: www
    aux_db:
        host: localhost
        db_name: aux_www
    jira:
        user: auto
        password: automenow
